### ISSUE TITLE
Timeout too fast

### ISSUE THREAD

**Issue by de4su** [NiekNijland/CSGO-Translator#10]
Hi, can u build a proxy switcher so  we don't get timeout after 2 minutes of use? there are some really raging kids in cs that write too much and too fast.

**Comment by NiekNijland** [comment]
Hi @de4su,

I have added translation caching in the latest release, this reduces the amount of google translate requests made.

Perhaps in the future I might add support for the [official Google Translate API](https://cloud.google.com/translate). Which has a free tier of up to 500.000 character per month. 

As of now I have no plans to make a system with proxies, but if you, or someone else still feels a need for this the repo is open for pull requests.
