### ISSUE TITLE
Other Src Games

### ISSUE THREAD

**Issue by nameonascreen** [NiekNijland/CSGO-Translator#3]
I need help converting this to work with other source games, L4D2 to be exact.
This would help out greatly since theres no region lock on l4d2. I get a lot of spanish only speaking players and would love to understand / somewhat learn what theyre saying so it becomes memory to me when they say something common.

**Comment by nameonascreen** [comment]
I've managed to get it to read L4D2's console.log but it doesn't seem to understand l4d2s messages.

**Comment by NiekNijland** [comment]
@nameonascreen you probably need to change the LineCleaner function in LogController.cs because the messaging syntax is different. Can you provide some messaging log lines from L4D2?

**Comment by nameonascreen** [comment]
_screen names paused the game
screen names  :  1
screen names unpaused the game
screen names  :  hola
screen names  :  hi_

this is taken straight from the console.log

**Comment by nameonascreen** [comment]
Oddly enough, it picks this up.

Opened Steam Socket NS_SERVER ( virtual port 27015 ) : listen socket handle( 1 )
Opened Steam Socket NS_CLIENT ( virtual port 27005 ) : listen socket handle( 65538 )
![a75dde95f0b52d8b35a11bae9f652ca9](https://user-images.githubusercontent.com/73326539/103833372-b5e36700-5035-11eb-8841-76eb5d249c84.png)

**Comment by nameonascreen** [comment]
Nvm, i figured it out! Finally got it to work. Thanks for the help.
