### ISSUE TITLE
traditional Chinese 2-char abbreviation

### ISSUE THREAD

**Issue by lauw0129** [NiekNijland/CSGO-Translator#7]
I want to ask what is the 2-char abbreviation of traditional Chinese? Because it must be zh-tw or hk but it's not working and the language option only can type two letter.

**Comment by NiekNijland** [comment]
For Chinese (simplified) the official Google Translate abbreviation is zh-CN. But cn also works. You can look up / test abbreviations using the Google Translate website.

![image](https://user-images.githubusercontent.com/43474728/114860442-4a572580-9dec-11eb-80d2-b7412ca1d018.png)

**Comment by lauw0129** [comment]
Thanks for help and the it is longer than 2 characters, hope it can fix in next update.
![image](https://user-images.githubusercontent.com/62137079/114861631-14cc2f80-9e20-11eb-8632-48a7ce4ec64e.png)

**Comment by lauw0129** [comment]
thanks for help and it is longer than 2 characters. Hope it can fix in next update
![image](https://user-images.githubusercontent.com/62137079/114861762-480ebe80-9e20-11eb-832c-fbc7c8326d92.png)

**Comment by NiekNijland** [comment]
Hi @lauw0129,

I have fixed this in version 3.0 that I just released.
